const {
  SCHEMA_VERSION,
  UNIFIED_SYNC_STATES,
  normalizeSessionScope,
  deriveActionScope,
  actionMatchesScope,
  filterActionsForScope,
  pruneCompletedPhotoUploadActions,
  hasQueueCapacity,
  MAX_QUEUE_ACTIONS,
  ACTION_SCOPE_VERSION,
} = require('./offline-sync/offlineSyncContext');
const {
  buildSyncSummary,
  formatSyncOutcome,
  setLastSuccessAt,
  getLastSuccessAt,
  formatLastSyncRelative,
  deriveUnifiedSyncStatus,
  getStalenessBucket,
  getStalenessLabel,
} = require('./offline-sync/syncStatusService');
const {
  saveTourPack,
  getTourPack,
  setTourPackMeta,
  getTourPackMeta,
  purgeTourPack,
} = require('./offline-sync/tourPackCacheService');
const {
  enqueueAction,
  getQueuedActions,
  updateAction,
  removeAction,
  getQueueStats,
  retryFailedActions,
  purgeActionsForScope,
  setActiveSessionScope,
  getActiveSessionScope,
  getQueueIsolationSummary,
  subscribeQueueState,
  subscribeQueuedActions,
} = require('./offline-sync/offlineQueueService');
const {
  replayQueue,
  getPhotoUploadActions,
} = require('./offline-sync/queueReplayService');

module.exports = {
  SCHEMA_VERSION,
  buildSyncSummary,
  formatSyncOutcome,
  setLastSuccessAt,
  getLastSuccessAt,
  formatLastSyncRelative,
  UNIFIED_SYNC_STATES,
  deriveUnifiedSyncStatus,
  saveTourPack,
  getTourPack,
  setTourPackMeta,
  getTourPackMeta,
  purgeTourPack,
  enqueueAction,
  getQueuedActions,
  updateAction,
  removeAction,
  getQueueStats,
  retryFailedActions,
  purgeActionsForScope,
  replayQueue,
  setActiveSessionScope,
  getActiveSessionScope,
  getQueueIsolationSummary,
  normalizeSessionScope,
  deriveActionScope,
  actionMatchesScope,
  filterActionsForScope,
  subscribeQueueState,
  subscribeQueuedActions,
  getPhotoUploadActions,
  getStalenessBucket,
  getStalenessLabel,
  pruneCompletedPhotoUploadActions,
  hasQueueCapacity,
  MAX_QUEUE_ACTIONS,
  ACTION_SCOPE_VERSION,
};
