export default function createDriverHomeScreenStyles({ StyleSheet, COLORS }) {
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  headerCard: {
    backgroundColor: COLORS.white,
    marginHorizontal: 20,
    marginTop: 16,
    padding: 16,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 4,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, marginRight: 12 },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: `${COLORS.primary}1A`,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  greeting: { color: COLORS.muted, fontSize: 12, fontWeight: '700', letterSpacing: 0.3 },
  driverName: { color: COLORS.text, fontSize: 20, fontWeight: '800' },
  iconButton: {
    backgroundColor: `${COLORS.primary}14`,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  content: { padding: 20, paddingBottom: 28 },
  inlineBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
  inlineBannerText: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  inlineBannerAction: {
    marginTop: 8,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  inlineBannerActionText: {
    fontSize: 13,
    fontWeight: '700',
  },
  inlineBannerDismiss: {
    padding: 2,
  },

  // Tour Assignment Card
  assignCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  cardLabel: { color: COLORS.muted, fontSize: 12, letterSpacing: 0.5, textTransform: 'uppercase', fontWeight: '700' },
  cardValue: { color: COLORS.text, fontSize: 20, fontWeight: '800', marginTop: 4 },
  cardHint: { color: COLORS.muted, fontSize: 13, marginTop: 6 },
  pillButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  pillButtonText: { color: COLORS.white, fontWeight: '700' },

  // Last Update Card
  lastUpdateCard: {
    backgroundColor: `${COLORS.success}08`,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: `${COLORS.success}30`,
  },
  lastUpdateHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  lastUpdateIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: `${COLORS.success}15`,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  lastUpdateTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.text,
  },
  lastUpdateTime: {
    fontSize: 12,
    color: COLORS.muted,
    marginTop: 2,
  },
  lastUpdateAddress: {
    fontSize: 13,
    color: COLORS.muted,
    marginTop: 10,
    lineHeight: 18,
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: `${COLORS.success}15`,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    gap: 5,
  },
  liveIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.success,
  },
  liveText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.success,
    textTransform: 'uppercase',
  },


  staleNudgeCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: `${COLORS.warning}12`,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: `${COLORS.warning}4D`,
  },
  staleNudgeIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: `${COLORS.warning}22`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  staleNudgeTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 4,
  },
  staleNudgeSubtitle: {
    fontSize: 12,
    color: COLORS.muted,
    lineHeight: 17,
  },
  autoShareCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    marginBottom: 6,
  },
  autoShareTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 3,
  },
  autoShareSubtitle: {
    fontSize: 12,
    color: COLORS.muted,
    lineHeight: 16,
  },
  autoShareStatus: {
    fontSize: 12,
    color: COLORS.primary,
    fontWeight: '600',
    marginBottom: 2,
  },
  autoShareLastRun: {
    fontSize: 12,
    color: COLORS.muted,
    marginBottom: 14,
  },
  // Grid and Buttons
  grid: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  bigButton: {
    flex: 1,
    borderRadius: 16,
    padding: 16,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  primaryTile: {
    backgroundColor: COLORS.primary,
    borderColor: `${COLORS.primary}80`,
  },
  chatTile: {
    backgroundColor: COLORS.white,
  },
  tileIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: `${COLORS.white}33`,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  bigButtonTitle: { fontSize: 16, fontWeight: '800', color: COLORS.white },
  bigButtonSubtitle: { fontSize: 13, color: '#E2E8F0', marginTop: 2 },
  tileBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    gap: 4,
  },
  tileBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.success,
  },

  stackButtons: { gap: 12 },
  wideButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  outlineButton: {
    backgroundColor: `${COLORS.primary}0A`,
    borderColor: `${COLORS.primary}4D`,
  },
  dangerButton: {
    backgroundColor: COLORS.danger,
    borderColor: `${COLORS.danger}80`,
  },
  infoButton: {
    backgroundColor: COLORS.info,
    borderColor: `${COLORS.info}80`,
  },
  purpleButton: {
    backgroundColor: COLORS.purple,
    borderColor: `${COLORS.purple}80`,
  },
  amberButton: {
    backgroundColor: '#D97706',
    borderColor: '#B4570980',
  },
  wideTitle: { fontSize: 16, fontWeight: '800', color: COLORS.text },
  wideSubtitle: { fontSize: 13, color: COLORS.muted },

  // Preview Modal
  previewModalContainer: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  previewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  previewCloseButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.text,
  },
  mapPreviewContainer: {
    height: 280,
    position: 'relative',
  },
  mapPreview: {
    flex: 1,
  },
  previewMarker: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: COLORS.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  accuracyBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    gap: 5,
  },
  accuracyText: {
    fontSize: 12,
    fontWeight: '600',
  },
  previewDetails: {
    flex: 1,
    padding: 20,
  },
  previewDetailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  previewDetailIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: `${COLORS.primary}12`,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  previewDetailText: {
    flex: 1,
  },
  previewDetailLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  previewDetailValue: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.text,
    marginTop: 4,
    lineHeight: 22,
  },
  refetchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: `${COLORS.primary}12`,
    borderRadius: 12,
    gap: 8,
    alignSelf: 'center',
    marginTop: 10,
  },
  refetchText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.primary,
  },
  previewActions: {
    flexDirection: 'row',
    gap: 12,
    padding: 20,
    paddingTop: 0,
  },
  cancelPreviewButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 14,
    backgroundColor: `${COLORS.muted}15`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelPreviewText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.muted,
  },
  confirmPreviewButton: {
    flex: 2,
    flexDirection: 'row',
    paddingVertical: 16,
    borderRadius: 14,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  confirmPreviewText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.white,
  },

  // Join Tour Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    padding: 20
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    elevation: 5,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12, alignItems: 'center' },
  modalTitle: { fontSize: 20, fontWeight: '800', color: COLORS.text },
  modalDesc: { color: COLORS.muted, marginBottom: 16, lineHeight: 20 },
  input: {
    backgroundColor: '#F8FAFC',
    padding: 14,
    borderRadius: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 18
  },
  modalBtn: {
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: COLORS.success,
  },
  modalBtnText: { color: COLORS.white, fontWeight: '800', fontSize: 15 },

  // Success Overlay
  successOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  successContent: {
    alignItems: 'center',
  },
  successText: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.success,
    marginTop: 16,
  },
});
}
