export default function createDriverTourPackScreenStyles({ StyleSheet, COLORS }) {
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.background },
  top: { flexDirection: 'row', alignItems: 'center', padding: 8, gap: 8 },
  topTitle: { fontSize: 18, fontWeight: '800', color: COLORS.textPrimary },
  tabs: { flexDirection: 'row', borderBottomWidth: 1, borderColor: COLORS.border },
  tab: { minHeight: 48, flex: 1, alignItems: 'center', justifyContent: 'center' },
  selectedTab: { borderBottomWidth: 3, borderColor: COLORS.primary },
  tabText: { fontWeight: '700', color: COLORS.textSecondary },
  selectedTabText: { color: COLORS.primary },
  content: { padding: 16, paddingBottom: 34, gap: 16 },
  hero: { backgroundColor: COLORS.primary, borderRadius: 16, padding: 18, gap: 6 },
  eyebrow: { color: '#DCEBFF', fontWeight: '800', fontSize: 12 },
  title: { fontSize: 24, fontWeight: '800', color: '#FFFFFF' },
  heroText: { color: '#FFFFFF' },
  section: { gap: 8 },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: COLORS.textPrimary },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  metric: { width: '48%', backgroundColor: '#FFFFFF', borderRadius: 10, padding: 12, minHeight: 80 },
  metricValue: { fontSize: 18, fontWeight: '800', color: COLORS.textPrimary },
  muted: { color: COLORS.textSecondary, lineHeight: 19 },
  mutedCentered: { color: COLORS.textSecondary, lineHeight: 20, textAlign: 'center' },
  card: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 13, gap: 6 },
  emptyCard: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 13 },
  cardTitle: { fontWeight: '700', color: COLORS.textPrimary },
  warning: { backgroundColor: '#FFF7E6', padding: 12, borderRadius: 10 },
  warningText: { color: '#92400E', lineHeight: 20 },
  critical: { backgroundColor: '#FEF2F2', padding: 12, borderRadius: 10 },
  criticalText: { color: '#991B1B', fontWeight: '700', lineHeight: 20 },
  ok: { backgroundColor: '#ECFDF3', padding: 12, borderRadius: 10 },
  okText: { color: '#166534', lineHeight: 20 },
  button: { minHeight: 48, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10, backgroundColor: '#EEF5FF', flexDirection: 'row', alignItems: 'center', gap: 7, alignSelf: 'flex-start' },
  buttonSelected: { borderWidth: 2, borderColor: COLORS.primary },
  buttonDisabled: { opacity: 0.55 },
  buttonText: { fontWeight: '700', color: COLORS.primary },
  buttonTextDisabled: { color: COLORS.textSecondary },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  pill: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 8, paddingVertical: 4, alignSelf: 'flex-start', backgroundColor: '#FFFFFF' },
  pillText: { fontWeight: '800', fontSize: 12 },
  timeline: { flexDirection: 'row', gap: 10, paddingVertical: 9 },
  dot: { width: 12, height: 12, borderRadius: 6, backgroundColor: COLORS.primary, marginTop: 4 },
  grow: { flex: 1 },
  note: { color: COLORS.textPrimary, lineHeight: 20 },
  fieldLabel: { color: COLORS.textPrimary, fontWeight: '800', marginTop: 4 },
  issueInput: { minHeight: 112, borderWidth: 1, borderColor: COLORS.border, borderRadius: 10, backgroundColor: '#FFFFFF', color: COLORS.textPrimary, padding: 12, textAlignVertical: 'top' },
  feedback: { color: '#166534', fontWeight: '700', lineHeight: 20 },
  itineraryLabel: { color: COLORS.textSecondary, fontWeight: '800', fontSize: 11 },
  person: { flexDirection: 'row', gap: 8, justifyContent: 'space-between', paddingVertical: 9, borderTopWidth: 1, borderColor: '#EEF0F3' },
  actionFeedback: { marginHorizontal: 16, marginTop: 10 },
  seatMap: { gap: 8 },
  coachDirection: { color: COLORS.textSecondary, fontSize: 11, fontWeight: '800', letterSpacing: 0.8, textAlign: 'center' },
  seatRow: { flexDirection: 'row', alignItems: 'stretch', width: '100%' },
  seatSide: { flex: 1, flexDirection: 'row', gap: 6 },
  aisle: { width: 26 },
  backSeatRow: { flexDirection: 'row', gap: 5, width: '100%' },
  seat: { flex: 1, minWidth: 0, minHeight: 64, borderWidth: 2, borderRadius: 10, alignItems: 'center', justifyContent: 'center', padding: 4 },
  backSeat: { minHeight: 60 },
  seatState: { fontSize: 11, fontWeight: '800', textAlign: 'center' },
  seatList: { backgroundColor: '#FFFFFF', borderRadius: 10, padding: 12, minHeight: 48, marginBottom: 7 },
  empty: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 28, gap: 14 },
  emptyTitle: { fontSize: 22, fontWeight: '800', color: COLORS.textPrimary, textAlign: 'center' },
});
}
