export default function createItineraryScreenStyles({ StyleSheet, COLORS, FONT_WEIGHT, Platform, RADIUS, SHADOWS, SPACING }) {
  return StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.appBackground },

  headerGradient: {
    paddingTop: Platform.OS === 'ios' ? 18 : 10,
    paddingBottom: 16,
    paddingHorizontal: 18,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
  },
  headerContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerTitleContainer: { flex: 1, minWidth: 0, marginHorizontal: 10 },
  headerLabel: { color: COLORS.lightBlueAccent, fontSize: 12, letterSpacing: 1.2, textTransform: 'uppercase', fontWeight: '700' },
  headerTitle: { flexShrink: 1, fontSize: 20, lineHeight: 25, fontWeight: '800', color: COLORS.white, marginTop: 2 },
  headerButton: { padding: 8, minWidth: 40, alignItems: 'center' },
  headerButtonDisabled: { opacity: 0.4 },
  headerIconButton: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  headerActions: { flexDirection: 'row', alignItems: 'center' },
  editButton: { backgroundColor: COLORS.white, borderRadius: 12 },
  readSummaryPanel: {
    marginTop: SPACING.md,
    padding: SPACING.md,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  readSummaryEyebrow: {
    color: COLORS.lightBlueAccent,
    fontSize: 11,
    fontWeight: FONT_WEIGHT.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  readSummaryTitle: {
    marginTop: 3,
    color: COLORS.white,
    fontSize: 20,
    lineHeight: 25,
    fontWeight: FONT_WEIGHT.extrabold,
  },
  summaryPillRow: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  summaryPill: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    backgroundColor: 'rgba(255,255,255,0.88)',
    paddingHorizontal: SPACING.sm,
    paddingVertical: 6,
  },
  summaryPillWide: {
    flexShrink: 1,
    maxWidth: '100%',
  },
  summaryPillText: {
    flexShrink: 1,
    color: COLORS.primaryBlue,
    fontSize: 12,
    fontWeight: FONT_WEIGHT.bold,
  },

  // Search Bar
  searchContainer: { marginTop: 12, backgroundColor: 'rgba(255,255,255,0.9)', borderRadius: 12, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', overflow: 'hidden' },
  searchInput: { flex: 1, marginLeft: 8, fontSize: 14, color: COLORS.darkText, paddingVertical: 12 },

  // Toolbar
  toolbar: { flexDirection: 'row', marginTop: 12, gap: 8, paddingTop: 12, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.2)' },
  toolbarButton: { flex: 1, minHeight: 34, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8, paddingVertical: 6, borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.15)' },
  toolbarText: { color: COLORS.white, fontSize: 12, fontWeight: '600', marginLeft: 6, flexShrink: 1 },

  // Day rail
  dayRailContainer: {
    backgroundColor: COLORS.appBackground,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingVertical: SPACING.sm,
  },
  dayRailContent: {
    paddingHorizontal: SPACING.lg,
    gap: SPACING.sm,
  },
  dayRailChip: {
    width: 122,
    minHeight: 58,
    justifyContent: 'center',
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.sm,
    ...SHADOWS.sm,
  },
  dayRailChipToday: {
    borderColor: COLORS.coralAccent,
    backgroundColor: COLORS.accentLight,
  },
  dayRailTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING.xs,
  },
  dayRailDayText: {
    color: COLORS.darkText,
    fontSize: 13,
    fontWeight: FONT_WEIGHT.extrabold,
  },
  dayRailDayTextToday: {
    color: COLORS.coralAccent,
  },
  dayRailTodayDot: {
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.coralAccent,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  dayRailTodayText: {
    color: COLORS.white,
    fontSize: 9,
    fontWeight: FONT_WEIGHT.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  dayRailDateText: {
    marginTop: 4,
    color: COLORS.secondaryText,
    fontSize: 12,
    fontWeight: FONT_WEIGHT.semibold,
  },
  dayRailDateTextToday: {
    color: COLORS.darkText,
  },

  scrollContainer: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 40 },

  // Sync Status
  syncStatusStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    marginBottom: SPACING.md,
    ...SHADOWS.sm,
  },
  syncStatusStripWarning: {
    borderColor: '#FCD34D',
    backgroundColor: '#FFFBEB',
  },
  syncStatusStripCritical: {
    borderColor: '#FCA5A5',
    backgroundColor: '#FEF2F2',
  },
  syncStatusIcon: {
    width: 34,
    height: 34,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primaryMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: SPACING.sm,
  },
  syncStatusIconWarning: {
    backgroundColor: '#FEF3C7',
  },
  syncStatusIconCritical: {
    backgroundColor: '#FEE2E2',
  },
  syncStatusTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  syncStatusLabel: {
    color: COLORS.primaryBlue,
    fontSize: 13,
    fontWeight: FONT_WEIGHT.extrabold,
  },
  syncStatusLabelWarning: {
    color: '#B45309',
  },
  syncStatusLabelCritical: {
    color: COLORS.danger,
  },
  syncStatusDetail: {
    marginTop: 2,
    color: COLORS.secondaryText,
    fontSize: 12,
    fontWeight: FONT_WEIGHT.semibold,
  },
  syncRetryButton: {
    minHeight: 36,
    minWidth: 58,
    marginLeft: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.primaryBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  syncRetryText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: FONT_WEIGHT.bold,
  },

  // Error Banner
  errorBanner: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.danger, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 12, marginBottom: 16 },
  errorText: { color: COLORS.white, fontSize: 13, fontWeight: '600', marginLeft: 8, flex: 1 },
  successBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    borderWidth: 1,
    borderColor: '#86EFAC',
    backgroundColor: '#F0FDF4',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.md,
  },
  successBannerText: {
    flex: 1,
    color: '#166534',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: FONT_WEIGHT.semibold,
  },
  offlineEditBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.sm,
    borderWidth: 1,
    borderColor: '#FCD34D',
    backgroundColor: '#FFFBEB',
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.md,
  },
  offlineEditText: {
    flex: 1,
    color: '#92400E',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: FONT_WEIGHT.semibold,
  },
  conflictCard: {
    borderWidth: 1,
    borderColor: '#FCA5A5',
    backgroundColor: '#FFF7F7',
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    marginBottom: SPACING.lg,
    ...SHADOWS.sm,
  },
  conflictHeadingRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  conflictIconWrap: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.full,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: SPACING.sm,
  },
  conflictHeadingText: { flex: 1 },
  conflictTitle: {
    color: '#991B1B',
    fontSize: 16,
    lineHeight: 21,
    fontWeight: FONT_WEIGHT.extrabold,
  },
  conflictSubtitle: {
    marginTop: 3,
    color: '#7F1D1D',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: FONT_WEIGHT.semibold,
  },
  conflictHelp: {
    marginTop: SPACING.md,
    color: COLORS.secondaryText,
    fontSize: 13,
    lineHeight: 19,
  },
  conflictActions: {
    flexDirection: 'row',
    gap: SPACING.sm,
    marginTop: SPACING.md,
  },
  conflictButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: SPACING.sm,
  },
  conflictPrimaryButton: { backgroundColor: COLORS.primaryBlue },
  conflictSecondaryButton: {
    borderWidth: 1,
    borderColor: COLORS.danger,
    backgroundColor: COLORS.white,
  },
  conflictPrimaryText: { color: COLORS.white, fontSize: 13, fontWeight: FONT_WEIGHT.bold },
  conflictSecondaryText: { color: COLORS.danger, fontSize: 13, fontWeight: FONT_WEIGHT.bold },

  // Loading Skeleton
  skeletonContainer: { paddingHorizontal: 16, paddingTop: 20 },
  skeletonCard: { backgroundColor: COLORS.white, borderRadius: 20, padding: 20, marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 3 },
  skeletonHeader: { height: 24, backgroundColor: '#E2E8F0', borderRadius: 8, marginBottom: 16, width: '60%' },
  skeletonLine: { height: 16, backgroundColor: '#F1F5F9', borderRadius: 6, marginBottom: 10 },

  // Empty State
  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 60, paddingHorizontal: 40 },
  emptyTitle: { fontSize: 22, fontWeight: '800', color: COLORS.darkText, marginTop: 20, marginBottom: 8 },
  emptySubtitle: { fontSize: 15, color: COLORS.secondaryText, textAlign: 'center', lineHeight: 22 },
  emptyButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.primaryBlue, paddingHorizontal: 24, paddingVertical: 14, borderRadius: 12, marginTop: 24, shadowColor: COLORS.primaryBlue, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
  emptyButtonText: { color: COLORS.white, fontSize: 16, fontWeight: '700', marginLeft: 8 },
  emptySecondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    marginTop: SPACING.xl,
    borderWidth: 1,
    borderColor: COLORS.primaryBlue,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.white,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    ...SHADOWS.sm,
  },
  emptySecondaryButtonText: {
    color: COLORS.primaryBlue,
    fontSize: 15,
    fontWeight: FONT_WEIGHT.bold,
  },


  dateWarningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: COLORS.appBackground,
  },
  dateWarningText: {
    color: COLORS.secondaryText,
    fontSize: 12,
  },

  // Day Cards
  dayCard: { backgroundColor: 'transparent', borderRadius: RADIUS.lg, marginBottom: SPACING.lg, ...SHADOWS.md },
  editingCard: { borderWidth: 2, borderColor: COLORS.primaryBlue, borderStyle: 'dashed' },
  todayCard: { borderWidth: 2, borderColor: COLORS.coralAccent, shadowColor: COLORS.coralAccent, shadowOpacity: 0.15 },
  dayCardInner: { borderRadius: RADIUS.lg, paddingHorizontal: SPACING.lg, paddingVertical: SPACING.lg },

  dayHeader: { flexDirection: 'row', alignItems: 'center' },
  dayBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.primaryBlue, paddingVertical: 8, paddingHorizontal: 14, borderRadius: 12 },
  todayBadge: { backgroundColor: COLORS.coralAccent },
  dayBadgeText: { fontSize: 13, fontWeight: '800', color: COLORS.white, letterSpacing: 0.3 },
  dayEditActions: { flexDirection: 'row', gap: 8 },
  dayActionButton: { padding: 8 },
  readDayHeader: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
  },
  readDayTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  readDayTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  readDayTitle: {
    color: COLORS.darkText,
    fontSize: 20,
    lineHeight: 25,
    fontWeight: FONT_WEIGHT.extrabold,
  },
  readDayDateText: {
    marginTop: 2,
    color: COLORS.secondaryText,
    fontSize: 13,
    fontWeight: FONT_WEIGHT.semibold,
  },
  readDayMetaText: {
    marginTop: 5,
    color: COLORS.mutedText,
    fontSize: 12,
    fontWeight: FONT_WEIGHT.semibold,
  },
  todayInlineBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.accentLight,
    borderWidth: 1,
    borderColor: COLORS.coralAccent,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
  },
  todayInlineBadgeText: {
    color: COLORS.coralAccent,
    fontSize: 10,
    fontWeight: FONT_WEIGHT.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  readDayChevron: {
    width: 34,
    height: 34,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.appBackground,
  },

  // Day content
  contentContainer: { marginTop: SPACING.md, paddingTop: SPACING.md, borderTopWidth: 1, borderTopColor: '#F1F5F9' },
  dayContentText: { fontSize: 15, color: COLORS.darkText, lineHeight: 24, letterSpacing: 0.1 },
  timelineList: {
    gap: SPACING.xs,
  },
  timelineItem: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderWidth: 1,
    borderColor: 'transparent',
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.sm,
    paddingRight: SPACING.sm,
  },
  timelineMarkerColumn: {
    width: 34,
    alignItems: 'center',
    alignSelf: 'stretch',
    position: 'relative',
  },
  timelineConnector: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 16,
    width: 2,
    borderRadius: RADIUS.full,
    backgroundColor: '#DBEAFE',
  },
  timelineConnectorFirst: {
    top: 18,
  },
  timelineConnectorLast: {
    bottom: 18,
  },
  timelineConnectorHidden: {
    display: 'none',
  },
  timelineIconCircle: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primaryMuted,
    borderWidth: 1,
    borderColor: '#BFDBFE',
    zIndex: 1,
  },
  timelineTextColumn: {
    flex: 1,
    minWidth: 0,
    paddingTop: 3,
    paddingLeft: SPACING.sm,
  },
  timelineTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.sm,
  },
  timelineItemText: {
    flex: 1,
    color: COLORS.darkText,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: FONT_WEIGHT.medium,
  },
  emptyDayPanel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.appBackground,
    padding: SPACING.md,
  },
  emptyDayText: {
    flex: 1,
    color: COLORS.secondaryText,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: FONT_WEIGHT.semibold,
  },

  // Edit mode
  editContentInput: {
    fontSize: 15,
    color: COLORS.darkText,
    lineHeight: 24,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    padding: 14,
    minHeight: 100,
    backgroundColor: '#F9FAFB',
    textAlignVertical: 'top',
  },

  addDayBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 18, marginTop: 12, marginBottom: 20, backgroundColor: COLORS.primaryBlue, borderRadius: 16, shadowColor: COLORS.primaryBlue, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.3, shadowRadius: 10, elevation: 6 },
  addDayText: { color: COLORS.white, fontWeight: '800', marginLeft: 10, fontSize: 16 },

  footerSpacer: { height: 20 },
});
}
