export default function createLoginScreenStyles({ StyleSheet, COLORS, FONT_WEIGHT, RADIUS, SHADOWS, SPACING }) {
  return StyleSheet.create({
  gradient: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: 'transparent' },
  keyboardAvoidingContainer: { flex: 1 },
  scrollContainer: { flexGrow: 1, justifyContent: 'flex-start', paddingTop: SPACING.xs, paddingHorizontal: SPACING.xl, paddingBottom: SPACING.xxl },
  scrollContainerKeyboardVisible: { justifyContent: 'flex-start', paddingBottom: SPACING.lg },
  container: { flexGrow: 1 },
  logoSection: {
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  logoImage: { marginBottom: SPACING.md },
  appTitle: {
    width: '100%',
    fontSize: 32,
    fontWeight: FONT_WEIGHT.extrabold,
    color: COLORS.white,
    letterSpacing: 0.3,
    lineHeight: 38,
    textAlign: 'center',
  },
  appSubtitle: {
    width: '100%',
    marginTop: 2,
    fontSize: 14,
    color: COLORS.lightBlue,
    fontWeight: FONT_WEIGHT.medium,
    textAlign: 'center',
  },
  formCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    padding: SPACING.xxl,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...SHADOWS.xl,
  },
  welcomeText: {
    width: '100%',
    fontSize: 24,
    fontWeight: FONT_WEIGHT.extrabold,
    color: COLORS.darkText,
    textAlign: 'center',
  },
  welcomeSubtext: {
    marginTop: SPACING.sm,
    marginBottom: SPACING.md,
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.subtleText,
  },
  networkPillBase: {
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderRadius: RADIUS.full,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.xs,
  },
  networkPillOnline: {
    backgroundColor: COLORS.successSoft,
    borderColor: COLORS.success,
  },
  networkPillOffline: {
    backgroundColor: COLORS.warningSoft,
    borderColor: COLORS.warning,
  },
  networkPillText: {
    fontSize: 12,
    fontWeight: FONT_WEIGHT.semibold,
  },
  hintsRow: { flexDirection: 'row', gap: SPACING.sm, marginBottom: SPACING.md },
  hintChip: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    backgroundColor: COLORS.inputBackground,
  },
  hintChipSelected: {
    borderColor: COLORS.primaryBlue,
    backgroundColor: COLORS.lightBlue,
  },
  hintTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  hintChipLabel: { fontSize: 12, fontWeight: FONT_WEIGHT.bold, color: COLORS.subtleText },
  hintChipLabelSelected: { color: COLORS.primaryBlue },
  hintChipText: {
    fontSize: 11,
    marginTop: SPACING.xs,
    color: COLORS.subtleText,
    lineHeight: 14,
  },
  hintChipTextSelected: { color: COLORS.darkText },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.inputBackground,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: SPACING.md,
    minHeight: 54,
  },
  inputContainerFocused: {
    borderColor: COLORS.primaryBlue,
    backgroundColor: COLORS.lightBlue,
  },
  inputIcon: { marginLeft: SPACING.md },
  input: {
    flex: 1,
    height: 52,
    paddingHorizontal: SPACING.md,
    fontSize: 16,
    color: COLORS.darkText,
    fontWeight: FONT_WEIGHT.semibold,
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: SPACING.md,
    gap: SPACING.sm,
    backgroundColor: COLORS.errorSoft,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.errorRed,
    padding: SPACING.sm,
  },
  errorBody: { flex: 1 },
  errorTitle: { color: COLORS.errorRed, fontSize: 14, fontWeight: FONT_WEIGHT.bold },
  errorText: {
    color: COLORS.errorRed,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  recoveryStepText: { color: COLORS.errorRed, fontSize: 12, lineHeight: 16, marginTop: 4 },
  errorActionsContainer: { marginTop: SPACING.sm, gap: SPACING.sm },
  errorActionButton: {
    borderWidth: 1,
    borderColor: COLORS.errorRed,
    borderRadius: RADIUS.sm,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    backgroundColor: COLORS.white,
  },
  errorActionText: { color: COLORS.errorRed, fontSize: 13, fontWeight: FONT_WEIGHT.semibold },
  button: {
    borderRadius: RADIUS.md,
    overflow: 'hidden',
    ...SHADOWS.lg,
  },
  buttonGradient: {
    minHeight: 54,
    paddingHorizontal: SPACING.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.xs,
  },
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
  },
  buttonDisabled: { opacity: 0.72 },
  buttonText: { color: COLORS.white, fontSize: 17, fontWeight: FONT_WEIGHT.bold },
  disclosureButton: {
    marginTop: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  disclosureButtonCompact: {
    marginTop: SPACING.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  disclosureText: { color: COLORS.primaryBlue, fontSize: 13, fontWeight: FONT_WEIGHT.semibold },
  disclosureErrorText: { color: COLORS.errorRed, fontSize: 13, fontWeight: FONT_WEIGHT.semibold },
  helpPanel: {
    marginTop: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.sm,
    padding: SPACING.sm,
    backgroundColor: COLORS.inputBackground,
  },
  helpText: {
    fontSize: 12,
    lineHeight: 17,
    color: COLORS.subtleText,
    marginBottom: 4,
  },
});
}
