export default function createNotificationPreferencesScreenStyles({ StyleSheet, COLORS, SHADOWS, THEME }) {
  return StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.appBackground,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 15,
    color: COLORS.secondaryText,
    textAlign: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: COLORS.headerBg,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.darkText,
  },
  headerButton: {
    padding: 4,
    minWidth: 40,
  },
  scrollContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  heroCard: {
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    ...SHADOWS.lg,
  },
  heroIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  heroTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: COLORS.white,
    lineHeight: 29,
  },
  heroSubtitle: {
    marginTop: 10,
    fontSize: 15,
    color: 'rgba(255,255,255,0.95)',
    lineHeight: 22,
  },
  permissionBadgeRow: {
    marginTop: 14,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: COLORS.white,
  },
  permissionBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  heroInfoCard: {
    marginTop: 14,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    padding: 12,
  },
  heroInfoTitle: {
    color: COLORS.white,
    fontWeight: '700',
    fontSize: 14,
  },
  heroInfoBody: {
    marginTop: 6,
    color: 'rgba(255,255,255,0.95)',
    fontSize: 13,
    lineHeight: 18,
  },
  introText: {
    fontSize: 16,
    color: COLORS.secondaryText,
    marginBottom: 20,
    textAlign: 'center',
  },
  healthCard: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 14,
    marginBottom: 18,
  },
  healthHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  healthHeaderText: { flex: 1 },
  healthTitle: {
    color: COLORS.darkText,
    fontSize: 15,
    fontWeight: '700',
  },
  healthSubtitle: {
    marginTop: 4,
    color: COLORS.secondaryText,
    fontSize: 12,
    lineHeight: 18,
  },
  healthScorePill: {
    borderRadius: 999,
    backgroundColor: THEME.primaryMuted,
    borderWidth: 1,
    borderColor: COLORS.lightBlueAccent,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  healthScoreText: {
    color: COLORS.primaryBlue,
    fontWeight: '800',
    fontSize: 12,
  },
  healthProgressTrack: {
    marginTop: 10,
    height: 8,
    borderRadius: 999,
    backgroundColor: COLORS.appBackground,
    overflow: 'hidden',
  },
  healthProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: COLORS.primaryBlue,
  },
  healthMetaRow: {
    marginTop: 10,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  healthMetaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.appBackground,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  healthMetaText: {
    fontSize: 12,
    fontWeight: '700',
  },
  healthSummaryText: {
    color: COLORS.secondaryText,
    fontSize: 12,
    fontWeight: '600',
  },
  statusBanner: {
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
  },
  successBanner: {
    backgroundColor: COLORS.successLight,
    borderColor: COLORS.successGreen,
  },
  errorBanner: {
    backgroundColor: COLORS.dangerLight,
    borderColor: COLORS.danger,
  },
  infoBanner: {
    backgroundColor: THEME.primaryMuted,
    borderColor: COLORS.lightBlueAccent,
  },
  statusBannerText: {
    color: COLORS.darkText,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  inlineActionButton: {
    marginTop: 10,
    alignSelf: 'flex-start',
    backgroundColor: COLORS.primaryBlue,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  inlineActionButtonText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '700',
  },
  lastSavedText: {
    fontSize: 13,
    color: COLORS.secondaryText,
    textAlign: 'center',
    marginBottom: 8,
  },
  section: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    ...SHADOWS.md,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.darkText,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 16,
    alignItems: 'flex-start',
  },
  sectionHeaderTextWrap: {
    flex: 1,
  },
  sectionSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: COLORS.secondaryText,
    lineHeight: 18,
  },
  sectionCountPill: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: COLORS.appBackground,
  },
  sectionCountText: {
    fontSize: 12,
    color: COLORS.secondaryText,
    fontWeight: '700',
  },
  sectionContent: {
    gap: 16,
  },
  subText: {
    fontSize: 14,
    color: COLORS.secondaryText,
    marginBottom: 12,
    lineHeight: 20,
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  labelContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    flex: 1,
  },
  labelTextWrap: { flex: 1 },
  labelTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  labelText: {
    fontSize: 15,
    color: COLORS.darkText,
    fontWeight: '600',
  },
  labelDescription: {
    marginTop: 3,
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.secondaryText,
  },
  labelBadge: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.primaryBlue,
    backgroundColor: THEME.primaryMuted,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  saveButton: {
    backgroundColor: COLORS.primaryBlue,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    ...SHADOWS.lg,
  },
  saveCard: {
    borderRadius: 14,
    padding: 14,
    marginTop: 10,
    ...SHADOWS.lg,
  },
  saveCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  saveCardHeaderText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '800',
  },
  saveCardBody: {
    color: 'rgba(255,255,255,0.92)',
    marginTop: 8,
    fontSize: 13,
    lineHeight: 19,
  },
  saveButtonOnGradient: {
    marginTop: 12,
    backgroundColor: COLORS.white,
    marginBottom: 0,
  },
  saveButtonTextOnGradient: {
    color: COLORS.primaryBlue,
    fontSize: 17,
    fontWeight: '800',
  },
  disabledButton: {
    opacity: 0.7,
  },
  noChangesCard: {
    marginTop: 10,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  noChangesText: {
    color: COLORS.secondaryText,
    fontSize: 14,
    fontWeight: '600',
  },
  saveButtonText: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: '700',
  },
  onboardingActionWrap: {
    marginTop: 8,
  },
  secondaryOnboardingButton: {
    marginTop: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingVertical: 12,
    backgroundColor: COLORS.white,
  },
  secondaryOnboardingButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.secondaryText,
  },
  // New Styles for Test Button
  testButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    padding: 10,
    gap: 8,
  },
  testButtonText: {
    color: COLORS.secondaryText,
    fontSize: 14,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  privacyNote: {
    textAlign: 'center',
    marginTop: 20,
    fontSize: 13,
    color: COLORS.tertiaryText,
  },
  permissionSummaryCard: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 14,
    marginBottom: 18,
  },
  permissionSummaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  permissionSummaryTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.secondaryText,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  permissionSummaryState: {
    marginTop: 8,
    fontSize: 16,
    fontWeight: '700',
  },
  permissionSummaryBody: {
    marginTop: 4,
    fontSize: 13,
    color: COLORS.secondaryText,
    lineHeight: 18,
  },
  presetRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    marginBottom: 4,
  },
  accordionTrigger: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    backgroundColor: COLORS.appBackground,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  accordionIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: THEME.primaryMuted,
  },
  accordionTextWrap: {
    flex: 1,
  },
  accordionTitle: {
    color: COLORS.darkText,
    fontSize: 15,
    fontWeight: '700',
  },
  accordionSubtitle: {
    marginTop: 3,
    color: COLORS.secondaryText,
    fontSize: 12,
    lineHeight: 17,
  },
  accordionMetaWrap: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 2,
  },
  accordionCountText: {
    color: COLORS.secondaryText,
    fontSize: 11,
    fontWeight: '700',
  },
  accordionContent: {
    gap: 16,
  },
  presetChip: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: COLORS.appBackground,
  },
  presetChipActive: {
    borderColor: COLORS.primaryBlue,
    backgroundColor: THEME.primaryMuted,
  },
  presetChipText: {
    fontSize: 12,
    color: COLORS.secondaryText,
    fontWeight: '700',
  },
  presetChipTextActive: {
    color: COLORS.primaryBlue,
  },
  emptyPanelContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  emptyPanel: {
    width: '100%',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    ...SHADOWS.md,
  },
  emptyPanelTitle: {
    marginTop: 12,
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.darkText,
  },
  emptyPanelMessage: {
    marginTop: 8,
    fontSize: 14,
    color: COLORS.secondaryText,
    textAlign: 'center',
    lineHeight: 20,
  },
  retryButton: {
    marginTop: 16,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: COLORS.primaryBlue,
  },
  retryButtonText: {
    color: COLORS.white,
    fontWeight: '700',
    fontSize: 14,
  },
});
}
