export default function createPassengerManifestScreenStyles({ StyleSheet, COLORS, FONT_WEIGHT, RADIUS, SHADOWS, SPACING }) {
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  header: {
    backgroundColor: COLORS.primaryDark,
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.md,
    justifyContent: 'space-between',
    gap: SPACING.sm,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  topBarTitleWrap: {
    flex: 1,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    paddingVertical: SPACING.xs,
  },
  backText: { color: COLORS.textLight, fontSize: 14, fontWeight: FONT_WEIGHT.bold, marginLeft: 5 },
  headerTitle: {
    color: COLORS.textLight,
    fontWeight: FONT_WEIGHT.extrabold,
    fontSize: 18,
  },
  headerSubtitle: {
    color: '#C7D2FE',
    marginTop: 2,
    fontSize: 12,
    fontWeight: FONT_WEIGHT.medium,
  },

  dashboardContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 0,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
  },
  progressRow: {
    flexDirection: 'row',
    gap: SPACING.xs,
    alignItems: 'stretch',
  },
  nextActionCard: {
    flex: 1,
    backgroundColor: COLORS.searchBg,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...SHADOWS.sm,
  },
  nextActionCardClear: {
    justifyContent: 'center',
  },
  nextActionClearText: {
    color: COLORS.success,
    fontSize: 12,
    fontWeight: FONT_WEIGHT.bold,
  },
  nextActionMeta: {
    flex: 1,
    paddingRight: SPACING.xs,
  },
  nextActionEyebrow: {
    fontSize: 10,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.info,
    marginBottom: 1,
  },
  nextActionTitle: {
    fontSize: 14,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.primaryDark,
  },
  dashboardItem: {
    flex: 1,
    alignItems: 'center',
  },
  dashDivider: {
    width: 1,
    height: '70%',
    backgroundColor: 'rgba(203, 213, 225, 0.35)',
  },
  dashLabel: {
    fontSize: 9,
    fontWeight: FONT_WEIGHT.bold,
    color: '#D1D5DB',
    marginBottom: 0,
    letterSpacing: 0.5,
  },
  dashValue: {
    fontSize: 17,
    fontWeight: FONT_WEIGHT.extrabold,
    color: COLORS.textLight,
  },
  dashSubValue: {
    marginTop: 1,
    fontSize: 10,
    color: '#E2E8F0',
    fontWeight: FONT_WEIGHT.semibold,
  },
  successTint: { color: '#BBF7D0' },
  dangerTint: { color: '#FECACA' },
  progressShell: {
    flex: 1.2,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: 'rgba(191, 219, 254, 0.45)',
    padding: SPACING.xs,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.xs,
  },
  progressTitle: {
    color: COLORS.textLight,
    fontWeight: FONT_WEIGHT.semibold,
    fontSize: 12,
  },
  progressValue: {
    color: COLORS.textLight,
    fontWeight: FONT_WEIGHT.bold,
    fontSize: 12,
  },
  progressTrack: {
    height: 6,
    borderRadius: RADIUS.full,
    backgroundColor: 'rgba(255,255,255,0.25)',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: RADIUS.full,
    backgroundColor: '#BFDBFE',
  },
  progressMeta: {
    marginTop: SPACING.xs,
    color: '#DBEAFE',
    fontSize: 11,
    fontWeight: FONT_WEIGHT.medium,
  },
  actionSearchRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
    alignItems: 'center',
  },
  filterToggle: {
    width: 44,
    height: 44,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...SHADOWS.sm,
  },
  filterToggleActive: {
    backgroundColor: COLORS.info,
    borderColor: COLORS.info,
  },
  filtersRow: {
    gap: SPACING.xs,
  },
  filterChipRow: {
    gap: SPACING.xs,
    paddingBottom: 2,
  },
  filterChip: {
    backgroundColor: COLORS.chipBg,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
    minHeight: 44,
    justifyContent: 'center',
  },
  filterChipActive: {
    backgroundColor: COLORS.chipActiveBg,
    borderColor: COLORS.chipActiveBg,
  },
  filterChipText: {
    color: COLORS.chipText,
    fontWeight: '700',
    fontSize: 12,
  },
  filterChipTextActive: {
    color: COLORS.chipActiveText,
  },
  statusBanner: {
    marginTop: 2,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  statusBanner_success: {
    borderColor: COLORS.success,
    backgroundColor: COLORS.successSoft,
  },
  statusBanner_warning: {
    borderColor: COLORS.warning,
    backgroundColor: COLORS.warningSoft,
  },
  statusBanner_error: {
    borderColor: COLORS.danger,
    backgroundColor: COLORS.dangerSoft,
  },
  statusBannerTextWrap: {
    flex: 1,
  },
  statusBannerText: {
    fontSize: 12,
    fontWeight: '700',
  },
  statusBannerText_success: {
    color: COLORS.success,
  },
  statusBannerText_warning: {
    color: COLORS.warning,
  },
  statusBannerText_error: {
    color: COLORS.danger,
  },
  statusBannerBtn: {
    borderRadius: 999,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
  },
  statusBannerBtn_success: {
    backgroundColor: COLORS.success,
  },
  statusBannerBtn_warning: {
    backgroundColor: COLORS.warning,
  },
  statusBannerBtn_error: {
    backgroundColor: COLORS.danger,
  },
  statusBannerBtnText: {
    color: COLORS.chipActiveText,
    fontSize: 11,
    fontWeight: '700',
  },
  statusBannerDismiss: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },

  syncStatusPill: {
    flex: 0.8,
    backgroundColor: COLORS.warningSoft,
    borderColor: '#FCD34D',
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  syncStatusPill_error: {
    backgroundColor: COLORS.dangerSoft,
    borderColor: '#FCA5A5',
  },
  syncTextWrap: { flex: 1 },
  syncStatusText: {
    color: COLORS.panel,
    fontWeight: FONT_WEIGHT.semibold,
    fontSize: 11,
  },
  syncStatusMeta: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: FONT_WEIGHT.medium,
  },
  syncBtn: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs + 1,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.info,
  },
  syncBtnText: { color: COLORS.textLight, fontWeight: FONT_WEIGHT.bold, fontSize: 11 },
  conflictText: { color: '#FDE68A', marginBottom: 2, fontSize: 11, fontWeight: FONT_WEIGHT.semibold },
  searchContainer: {
    flex: 1,
    minHeight: 40,
    flexDirection: 'row',
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    ...SHADOWS.sm,
  },
  searchInput: {
    flex: 1,
    marginLeft: SPACING.xs,
    fontSize: 13,
    color: COLORS.primaryDark,
    fontWeight: FONT_WEIGHT.medium,
  },
  searchMetaRow: {
    marginTop: SPACING.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  searchMetaText: {
    color: '#E2E8F0',
    fontSize: 12,
    fontWeight: FONT_WEIGHT.semibold,
  },
  searchMetaDivider: {
    color: '#93C5FD',
    fontSize: 12,
    fontWeight: FONT_WEIGHT.bold,
  },

  listContent: { padding: SPACING.lg, paddingBottom: SPACING.xxxl },
  emptyStateCard: {
    margin: SPACING.lg,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.lg,
    padding: SPACING.xl,
    alignItems: 'center',
    ...SHADOWS.md,
  },
  emptyStateTitle: {
    marginTop: SPACING.sm,
    fontSize: 17,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.primaryDark,
  },
  emptyStateBody: {
    marginTop: SPACING.xs,
    fontSize: 13,
    color: COLORS.muted,
    textAlign: 'center',
    lineHeight: 18,
  },
  sectionHeader: {
    backgroundColor: '#EEF2FF',
    paddingVertical: SPACING.xs,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.sm,
    marginBottom: SPACING.xs,
    marginTop: SPACING.xs,
    borderWidth: 1,
    borderColor: '#C7D2FE',
  },
  sectionTitle: {
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.primaryDark,
    fontSize: 13,
  },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalKeyboardAvoider: { flex: 1 },
  modalContent: {
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    minHeight: 350,
    maxHeight: '92%',
  },
  modalBody: { flexShrink: 1 },
  modalBodyContent: { paddingBottom: SPACING.md },
  modalHeader: { marginBottom: 20, borderBottomWidth: 1, borderBottomColor: '#eee', paddingBottom: 15 },
  modalHeaderRow: { alignItems: 'center', flexDirection: 'row', gap: SPACING.md },
  modalHeaderText: { flex: 1 },
  modalTitle: { fontSize: 22, fontWeight: 'bold', color: COLORS.primary },
  modalSubtitle: { fontSize: 16, color: COLORS.muted, marginTop: 5 },
  phoneBookingBtn: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.md,
    flexDirection: 'row',
    gap: SPACING.xs,
    minHeight: 44,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
  },
  phoneBookingBtnText: {
    color: COLORS.textLight,
    fontSize: 15,
    fontWeight: FONT_WEIGHT.bold,
  },
  emptyStateRetryButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.md,
    flexDirection: 'row',
    gap: SPACING.xs,
    minHeight: 44,
    marginTop: SPACING.md,
    paddingHorizontal: SPACING.lg,
  },
  emptyStateRetryText: { color: COLORS.textLight, fontWeight: FONT_WEIGHT.bold },

  modalSectionLabel: { fontSize: 14, fontWeight: 'bold', color: COLORS.muted, marginBottom: 10, textTransform: 'uppercase', letterSpacing: 0.4 },
  actionRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 15, marginBottom: 15 },
  actionBtn: {
    flex: 1,
    paddingVertical: 20,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBtnText: { color: 'white', fontSize: 16, fontWeight: 'bold', marginTop: 5 },

  secondaryActionBtn: {
    padding: 15,
    borderRadius: 12,
    borderWidth: 2,
    alignItems: 'center',
    marginBottom: 20,
    borderStyle: 'dashed'
  },
  modalHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    marginBottom: SPACING.md,
    backgroundColor: COLORS.bg,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.sm,
  },
  modalHintText: {
    flex: 1,
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: FONT_WEIGHT.medium,
  },
  closeBtn: { padding: 15, alignItems: 'center' },
  closeBtnText: { color: COLORS.muted, fontWeight: 'bold', fontSize: 16 },

  passengerList: { gap: 10, marginBottom: 15 },
  passengerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.border
  },
  passengerName: { fontWeight: 'bold', color: COLORS.primary },
  passengerSeat: { color: COLORS.muted, marginTop: 4 },
  passengerActions: { flexDirection: 'row', gap: 8 },
  statusPill: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: 'white'
  },
  statusPillText: { fontSize: 12, fontWeight: '600', color: COLORS.primary },
  statusPillActiveSuccess: { backgroundColor: '#ECFDF3', borderColor: '#BBF7D0' },
  statusPillActiveDanger: { backgroundColor: '#FEF2F2', borderColor: '#FECACA' },
  statusPillActivePending: { backgroundColor: '#EFF6FF', borderColor: '#BFDBFE' },
  statusPillTextActive: { color: COLORS.primary },
  partialFooter: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  partialFooterBtn: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    alignItems: 'center'
  },
  partialFooterCancel: {
    borderWidth: 1,
    borderColor: COLORS.info,
    backgroundColor: 'white'
  },
  partialFooterConfirm: {
    backgroundColor: COLORS.info
  },
  partialFooterText: { fontWeight: 'bold' }
});
}
