export default function createTourHomeScreenStyles({ StyleSheet, COLORS, RADIUS, SHADOWS, SPACING }) {
  return StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.appBackground,
  },
  statusBarSafeArea: {
    backgroundColor: COLORS.statusBarBackground,
  },
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.appBackground,
  },
  gradient: {
    flex: 1,
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.xxl,
  },

  // Header styles
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.lg,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    ...SHADOWS.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    zIndex: 20,
  },
  headerBrandMark: {
    width: 56,
    height: 56,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: `${COLORS.primaryBlue}08`,
  },
  logoImage: {
    width: 42,
    height: 42,
    borderRadius: 12,
  },
  headerTextContainer: {
    flex: 1,
    marginLeft: SPACING.md,
    marginRight: SPACING.md,
    minWidth: 0,
    justifyContent: 'center',
  },
  greetingTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    gap: 8,
    minWidth: 0,
  },
  greetingIconBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  greetingText: {
    flex: 1,
    minWidth: 0,
    fontSize: 20,
    color: COLORS.darkText,
    fontWeight: '800',
    lineHeight: 24,
  },
  headerActions: {
    position: 'relative',
    zIndex: 30,
    flexShrink: 0,
  },
  headerMenuButton: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: `${COLORS.primaryBlue}0D`,
    borderWidth: 1,
    borderColor: `${COLORS.primaryBlue}14`,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerMenuButtonActive: {
    backgroundColor: `${COLORS.primaryBlue}16`,
    borderColor: `${COLORS.primaryBlue}28`,
  },
  headerMenuDropdown: {
    position: 'absolute',
    top: 52,
    right: 0,
    width: 210,
    borderRadius: RADIUS.lg,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: `${COLORS.primaryBlue}16`,
    padding: 8,
    gap: 6,
    ...SHADOWS.xl,
  },
  headerMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: RADIUS.md,
    backgroundColor: `${COLORS.primaryBlue}08`,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  headerMenuIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: `${COLORS.primaryBlue}12`,
  },
  headerMenuItemText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.darkText,
  },

  // Countdown styles
  countdownContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: `${COLORS.primaryBlue}0D`,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.lg,
    marginBottom: SPACING.lg,
    gap: 10,
    borderWidth: 1,
    borderColor: `${COLORS.primaryBlue}18`,
  },
  countdownUrgent: {
    backgroundColor: COLORS.warningLight,
  },
  countdownVeryUrgent: {
    backgroundColor: COLORS.errorLight,
  },
  countdownText: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.primaryBlue,
  },
  countdownTextUrgent: {
    color: COLORS.error,
  },
  countdownFallbackContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.cardBackground,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    marginBottom: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  countdownFallbackText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.subtleText,
  },

  // Status card styles
  statusCard: {
    marginBottom: SPACING.lg,
    borderRadius: RADIUS.xl,
    overflow: 'hidden',
    ...SHADOWS.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  statusCardGradient: {
    flexDirection: 'row',
    padding: SPACING.lg,
    alignItems: 'flex-start',
  },
  statusIconContainer: {
    position: 'relative',
    marginRight: 16,
  },
  statusPulse: {
    position: 'absolute',
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  statusIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusContent: {
    flex: 1,
  },
  statusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 10,
  },
  statusBadgeText: {
    fontWeight: '800',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  statusTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.darkText,
    marginBottom: 6,
  },
  statusMessage: {
    fontSize: 14,
    color: COLORS.subtleText,
    lineHeight: 20,
  },

  // Quick actions styles
  quickActionsContainer: {
    marginBottom: SPACING.xl,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    ...SHADOWS.md,
    borderWidth: 1,
    borderColor: `${COLORS.primaryBlue}12`,
  },
  quickActionsTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.subtleText,
    marginBottom: 12,
    marginLeft: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  quickActionsSubtitle: {
    fontSize: 13,
    color: COLORS.subtleText,
    marginBottom: SPACING.md,
    marginHorizontal: 4,
    lineHeight: 18,
  },
  quickActionsRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  quickActionWrapper: {
    flex: 1,
    minWidth: 0,
  },
  quickActionWrapperCompact: {
    flexBasis: '47%',
    flexGrow: 1,
  },
  quickActionButton: {
    alignItems: 'center',
    width: '100%',
  },
  quickActionIconContainer: {
    width: 52,
    height: 52,
    borderRadius: RADIUS.lg,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    position: 'relative',
  },
  quickActionIconContainerCompact: {
    width: 46,
    height: 46,
    borderRadius: RADIUS.md,
    marginBottom: 6,
  },
  quickActionBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: COLORS.error,
    width: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quickActionBadgeText: {
    color: COLORS.white,
    fontSize: 10,
    fontWeight: '800',
  },
  quickActionLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.darkText,
    textAlign: 'center',
  },
  quickActionLabelCompact: {
    fontSize: 11,
  },

  // Boarding pass styles
  boardingPass: {
    marginBottom: SPACING.xl,
    borderRadius: RADIUS.xl,
    overflow: 'hidden',
    backgroundColor: COLORS.white,
    ...SHADOWS.xl,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  boardingPassHeader: {
    paddingHorizontal: SPACING.xl,
    paddingTop: SPACING.xl,
    paddingBottom: SPACING.xxl,
  },
  boardingPassHeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  boardingPassHeaderTextContainer: {
    flex: 1,
    minWidth: 0,
    marginRight: 12,
  },
  boardingPassLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.7)',
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  boardingPassTour: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.white,
  },
  boardingPassQR: {
    opacity: 0.9,
  },
  tornEdge: {
    flexDirection: 'row',
    height: 12,
    backgroundColor: COLORS.white,
    marginTop: -12,
  },
  tornEdgeBump: {
    flex: 1,
    height: 12,
    backgroundColor: COLORS.primaryBlue,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    marginHorizontal: 1,
  },
  boardingPassBody: {
    padding: SPACING.xl,
  },
  boardingPassDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginVertical: 16,
  },

  // Driver status styles
  driverStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  driverAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.primaryBlue,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  liveDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: COLORS.success,
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  driverInfo: {
    marginLeft: 12,
    flex: 1,
  },
  driverName: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.darkText,
    marginBottom: 2,
  },
  driverStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.subtleText,
  },
  statusDotLive: {
    backgroundColor: COLORS.success,
  },
  driverStatusText: {
    fontSize: 12,
    color: COLORS.subtleText,
    fontWeight: '500',
  },

  // Pickup section styles
  pickupSection: {
    marginBottom: 16,
  },
  pickupSectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.subtleText,
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  pickupCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: `${COLORS.primaryBlue}08`,
    padding: 14,
    borderRadius: 14,
    marginBottom: 8,
  },
  pickupTimeBox: {
    backgroundColor: COLORS.coralAccent,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    marginRight: 12,
  },
  pickupTimeText: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.white,
  },
  pickupLocationInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  pickupLocationCopy: {
    flex: 1,
  },
  pickupLocationText: {
    fontSize: 14,
    color: COLORS.darkText,
    fontWeight: '500',
    flex: 1,
    lineHeight: 20,
  },
  pickupDateText: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 17,
    color: COLORS.subtleText,
    fontWeight: '600',
  },

  // Seat section styles
  seatSection: {
    alignItems: 'center',
    marginBottom: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  seatGrid: {
    gap: 12,
    marginBottom: 8,
  },
  seatRow: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
  },
  seatBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: `${COLORS.coralAccent}15`,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    gap: 8,
  },
  seatNumber: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.coralAccent,
  },
  seatLabel: {
    fontSize: 12,
    color: COLORS.subtleText,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  // Passengers section styles
  passengersSection: {
    marginTop: 8,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  passengersSectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.subtleText,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  passengerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  passengerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.primaryBlue,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  passengerAvatarText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '700',
  },
  passengerName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.darkText,
  },
  passengerSeat: {
    fontSize: 12,
    color: COLORS.coralAccent,
    fontWeight: '700',
    backgroundColor: `${COLORS.coralAccent}15`,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },

  // Boarding pass footer styles
  boardingPassFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopStyle: 'dashed',
    borderTopColor: COLORS.border,
  },
  boardingPassFooterLabel: {
    fontSize: 10,
    color: COLORS.subtleText,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  boardingPassFooterValue: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.darkText,
  },
  boardingPassFooterRight: {
    alignItems: 'flex-end',
  },

  // Find My Bus card styles
  findBusCard: {
    marginBottom: SPACING.xl,
    borderRadius: RADIUS.xl,
    overflow: 'hidden',
    backgroundColor: COLORS.white,
    ...SHADOWS.lg,
    borderWidth: 1.5,
    borderColor: `${COLORS.coralAccent}30`,
  },
  findBusGradient: {
    padding: SPACING.lg,
  },
  findBusContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  findBusIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: `${COLORS.coralAccent}15`,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    position: 'relative',
  },
  findBusLiveBadge: {
    position: 'absolute',
    bottom: -6,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.success,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    gap: 4,
  },
  findBusLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.white,
  },
  findBusLiveText: {
    fontSize: 9,
    fontWeight: '800',
    color: COLORS.white,
    letterSpacing: 0.5,
  },
  findBusTextContainer: {
    flex: 1,
  },
  findBusTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.darkText,
    marginBottom: 4,
  },
  findBusSubtitle: {
    fontSize: 14,
    color: COLORS.subtleText,
    fontWeight: '500',
    lineHeight: 20,
  },
  findBusArrow: {
    marginLeft: 10,
  },

  // Section title
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.darkText,
    marginBottom: SPACING.lg,
    paddingLeft: 4,
  },

  // Features grid styles
  featuresGrid: {
    gap: SPACING.md,
  },
  featuresRow: {
    flexDirection: 'row',
    gap: SPACING.md,
  },
  featureCard: {
    flex: 1,
    borderRadius: RADIUS.lg,
    overflow: 'hidden',
    backgroundColor: COLORS.white,
    ...SHADOWS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  featureCardLarge: {
    borderRadius: RADIUS.lg,
    overflow: 'hidden',
    backgroundColor: COLORS.white,
    ...SHADOWS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  featureCardInner: {
    flex: 1,
  },
  featureCardGradient: {
    padding: SPACING.lg,
    minHeight: 130,
    justifyContent: 'space-between',
  },
  featureIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  featureCardTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.darkText,
    marginBottom: 2,
  },
  featureCardTitleLarge: {
    fontSize: 17,
  },
  featureCardSubtitle: {
    fontSize: 12,
    color: COLORS.subtleText,
    fontWeight: '500',
  },
  featureArrow: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.xxl,
  },
  modalCard: {
    width: '100%',
    maxWidth: 400,
    maxHeight: '92%',
    borderRadius: 24,
    overflow: 'hidden',
    ...SHADOWS.xl,
  },
  modalGradient: {
    maxHeight: '100%',
  },
  modalScrollView: {
    width: '100%',
  },
  modalScrollContent: {
    padding: 28,
    alignItems: 'center',
  },
  modalContinueButton: {
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: SPACING.md,
    marginTop: SPACING.sm,
  },
  modalContinueButtonText: {
    color: COLORS.primaryBlue,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  modalIconContainer: {
    position: 'relative',
    marginBottom: 20,
  },
  modalIconPulse: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.error,
    opacity: 0.2,
  },
  modalIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: `${COLORS.error}15`,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: COLORS.darkText,
    textAlign: 'center',
    marginBottom: 12,
  },
  modalMessage: {
    fontSize: 15,
    color: COLORS.subtleText,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 20,
  },
  modalDivider: {
    width: '100%',
    height: 1,
    backgroundColor: COLORS.border,
    marginBottom: 20,
  },
  modalActionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.subtleText,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 16,
  },
  modalPrimaryButton: {
    width: '100%',
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 12,
  },
  modalButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    gap: 10,
  },
  modalPrimaryButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '700',
  },
  modalSecondaryButton: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: `${COLORS.primaryBlue}10`,
    marginBottom: 12,
    gap: 10,
  },
  modalSecondaryButtonText: {
    color: COLORS.primaryBlue,
    fontSize: 15,
    fontWeight: '700',
  },
  modalEmergencyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 8,
  },
  modalEmergencyButtonText: {
    color: COLORS.error,
    fontSize: 14,
    fontWeight: '700',
  },
  modalLogoutDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginVertical: 12,
    marginHorizontal: 20,
  },
  modalLogoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 8,
  },
  modalLogoutButtonText: {
    color: COLORS.subtleText,
    fontSize: 14,
    fontWeight: '600',
  },
});
}
